### PR TITLE
AS_median_adjustment added

### PR DESCRIPTION
**Pull request by eulogepagui**
I added the function AS_median_adjustment in brglmFit. In addition, I modified brglmControl so that the option type could take value "AS_median".

### CODE REVIEW

**Comment by ikosmidis** [comment]
Looks good - can you send a few unit tests and include the formulae in the iteration vignette so that I can test everything out?

**Comment by eulogepagui** [comment]
Thanks. All possible unit test are ready and now, I am preparing the
iteration vignette and tomorrow I will pull a request as usual to you.

Talk to you soon,
Clovis

**Comment by ikosmidis** [comment]
Great! I will run the tests asap and come back to you after the wknd -I

**Comment by ikosmidis** [comment]
Now merged. I will send an email with what I've changed since your commits. I've added you on brglm2 so you can checkout and work directly on master

**Pull request merged**
